# Generated by Django 2.1.5 on 2020-03-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='filmID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Reviewer'),
        ),
    ]
