# Generated by Django 2.1.5 on 2020-03-21 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20200306_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.AlterField(
            model_name='rating',
            name='filmID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Film'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
