# Generated by Django 2.1.5 on 2020-03-22 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20200321_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='filmID',
            new_name='fkID',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='filmID',
            new_name='fkID',
        ),
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
