# Generated by Django 2.1.5 on 2020-03-27 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
