# Generated by Django 2.1.5 on 2020-03-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_reviewer_is_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='is_reviewer',
        ),
    ]
