# Generated by Django 2.1.5 on 2020-03-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_remove_reviewer_is_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewerID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Reviewer'),
        ),
    ]
