# Generated by Django 2.1.5 on 2020-03-31 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_auto_20200331_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='fkID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rango.Film'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Reviewer'),
        ),
    ]
